import javax.swing.*;
import java.awt.*;

public class Spidey extends JFrame {

    public JLabel text;

    public JButton spiderMan;
    public JButton normal_Spidey;
    public JLabel icon;
    public JLabel icon2;
    /*
    *Declaring components
    * These are needed to be placed inside the JFrame
    * Each button has a functionality
     */
    Spidey(){

        text = new JLabel("Spider-man");//Actual text
        text.setBounds(870,100,300,50);//Position
        text.setForeground(Color.WHITE);//Text color
        text.setFont(new Font("Cabin",Font.PLAIN,40));//Text font

        spiderMan = new JButton("Symbiote Spider-man");
        spiderMan.setBounds(600,280,300,150);
        spiderMan.setFont(new Font("Cabin",Font.BOLD,15));
        spiderMan.setFocusable(false);
        spiderMan.setForeground(Color.BLACK);
        spiderMan.setBackground(Color.white);

        normal_Spidey = new JButton("Normal Spider-man");
        normal_Spidey.setBounds(1050,280,300,150);
        normal_Spidey.setFont(new Font("Cabin",Font.BOLD,15));
        normal_Spidey.setFocusable(false);
        normal_Spidey.setForeground(Color.BLACK);
        normal_Spidey.setBackground(Color.white);

        /*
        *Button customization
        * This was inspired by Spider-man Trilogy
         */

        icon = new JLabel();
        icon.setBounds(550,370,700,750);
        icon.setVisible(false);

        icon2 = new JLabel();
        icon2.setBounds(1100,370,700,750);
        icon2.setVisible(false);

        /*
        *label visibility is edited on purpose in this way
        * By pressing the buttons the
         */

        ImageIcon image = new ImageIcon("C:\\Users\\STAGKOSARISTEIDIS\\Pictures\\Saved Pictures\\Spider.png");//Icon image of application
        this.setIconImage(image.getImage());//Generated by AI

        ImageIcon image2 = new ImageIcon("C:\\Users\\STAGKOSARISTEIDIS\\Pictures\\Saved Pictures\\BlackSpidey.jpg");//This picture were Google searched but for making the application purposes
        icon.setIcon(image2);//Inserting picture to label
        spiderMan.addActionListener(e -> icon.setVisible(true));//Most important lines

        ImageIcon image3 = new ImageIcon("C:\\Users\\STAGKOSARISTEIDIS\\Pictures\\Saved Pictures\\BlueandRed.jpg");//The same applies for this picture as well
        icon2.setIcon(image3);//Inserting picture to label
        normal_Spidey.addActionListener(e -> icon2.setVisible(true));//Second most important line

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//Terminating program by pressing x button on application
        this.setTitle("Spider-man");//Title of the application
        this.getContentPane().setBackground(new Color(0,0,0));//Background color
        this.setLayout(null);//Layout edited by the developer
        this.setSize(new Dimension(1920,1080));//Dimensions
        this.setVisible(true);//Setting Visibility application
        this.add(text);
        this.add(spiderMan);
        this.add(normal_Spidey);
        this.add(icon);
        this.add(icon2);
        /*
        *Adding the declared components
        * By pressing the buttons somebody is able to see Spider-man
         */
    }
}
